### ISSUE TITLE
Ps2keyboard not working on atmega1284 16mhz

### ISSUE THREAD

**Issue by Jarvis785** [MCUdude/MightyCore#68] opened 2017-11-24 12:14 UTC
Please anyone help..  ps2keyboard not working

**Comment by MCUdude** [comment] 2017-11-24 13:17
Really? How on earth should I be able to help you when you've provided _zero_ details?

**Comment by Jarvis785** [comment] 2017-11-24 13:30
Irq pin bobduino digital 2
Data pin A0

It's not receiving any key input

**Comment by MCUdude** [comment] 2017-11-24 14:41
I guess you've connected the keyboard to the wrong inputs on the microcontroller then? Try some other pins

**Comment by Jarvis785** [comment] 2017-11-24 14:48
I've tried different pins .. still not working . Anybody here worked with ps2keyboard on mightycore ?

**Comment by MCUdude** [comment] 2017-12-15 16:32
A quick look at the library source code reveals an easy error; support for ATmega1284p isn't added to the library. You can do so by modifying the [int_pins.h](https://github.com/PaulStoffregen/PS2Keyboard/blob/master/utility/int_pins.h) file.

Anyways I'm closing this issue because it has nothing to do with the MightyCore source code. It's caused by a third party library that I have no influence on. If you're still experiencing issues you should probably create an issue over at the library repo.

**Closed by MCUdude** 2017-12-15 16:32 UTC

**Comment by Jarvis785** [comment] 2017-12-15 18:49
Mcudude plese help me out can you plese send me a edited int_pins.h or tell me what lines to add to thw file . Please help me out

**Comment by drawkula** [comment] 2017-12-15 19:04
@Jarvis785 
Please open an issue about this at [https://github.com/PaulStoffregen/PS2Keyboard/issues](https://github.com/PaulStoffregen/PS2Keyboard/issues). That's where changes to that file should be made and documented.
